import { test, expect } from '@playwright/test';

test('karoza website', async ({ page }) => {
  await page.goto('https://kartoza.com/');
  await expect(page.locator('[id="quick\\ bio"]')).toContainText('Unlock insights from your data with the power of GIS');
  await expect(page.locator('[id="quick\\ bio"]')).toContainText('We do spatial IT.');
  await expect(page.locator('[id="quick\\ bio"]')).toContainText('We develop, implement and support systems with a spatial or location component.');
  await expect(page.locator('[id="quick\\ bio"]')).toContainText('We train people to use geospatial technology to its full potential.');
  await expect(page.getByRole('link', { name: 'Find your solution' })).toBeVisible();
  await expect(page.getByRole('img', { name: 'kartoza gis company' })).toBeVisible();
  await expect(page.getByPlaceholder('Search...')).toBeEmpty();
  await expect(page.getByRole('link', { name: 'Kartoza' })).toBeVisible();
  await expect(page.locator('#gis-skills > div').first()).toBeVisible();
  await expect(page.locator('#our-skills')).toContainText('Skill up with GIS tools and workflows');
  await expect(page.getByRole('img', { name: 'kartoza solutions' })).toBeVisible();
  await expect(page.locator('#our-skills')).toContainText('Build a solution');
  await expect(page.getByRole('img', { name: 'kartoza hosting' })).toBeVisible();
  await expect(page.locator('#our-skills')).toContainText('Host, deploy, maintain and support your tech');
  await expect(page.locator('#featured')).toContainText('A Selection of our Projects');
  await page.locator('span').nth(2).click();
  await expect(page.getByRole('img', { name: 'kartoza portfolio' })).toBeVisible();
  await page.locator('span').nth(3).click();
  await expect(page.getByRole('link', { name: 'View Project' })).toBeVisible();
  await expect(page.locator('#welcome')).toContainText('Why Kartoza?');
  await expect(page.locator('#welcome')).toContainText('We support Open Source geospatial software');
  await expect(page.locator('#welcome')).toContainText('Our team is available 24/7');
  await expect(page.locator('#welcome')).toContainText('All-in-one development, training and support');
  await expect(page.locator('#welcome')).toContainText('We’re trusted around the world');
  await expect(page.getByRole('link', { name: 'LEARN MORE' })).toBeVisible();
  await expect(page.locator('#footerwrap')).toContainText('About Kartoza');
  await expect(page.getByRole('link', { name: 'Crowdfunding' })).toBeVisible();
  await expect(page.locator('#footer-menu-contact').getByRole('link', { name: 'Contact' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Internships' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Policies' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'We\'re Hiring!' })).toBeVisible();
});